version: '3.9'

services:
  rethinkdb:
    image: rethinkdb:2.4
    expose:
      - 28015
    restart: always
    volumes:
      - ./server/db/exhibitions/data:/app
    networks:
      - net

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.0
    environment:
      - cluster.name=es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx4096m"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9200"]
        interval: 10s
        timeout: 2s
        retries: 10
        start_period: 30s
    volumes:
      - ./server/db/fulltext/data:/usr/share/elasticsearch/data
    expose:
      - 9200
    restart: always
    networks:
      - net

  qdrant:
    image: qdrant/qdrant:latest
    mem_limit: 4096m
    expose:
      - 6333
    volumes:
      - ./server/db/vectorspace/data:/qdrant/storage
    networks:
      - net

  server: 
    depends_on:
      elastic:
        condition: service_healthy
    build: 
      context: server
      dockerfile: Dockerfile
    expose: 
      - 3000
    restart: always
    networks:
      - net

  nginx:
    depends_on: 
      - server
    image: nginx:latest
    ports: 
        - 80:80
        - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./nginx/www/:/var/www/:rw
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - net

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  client:
    depends_on:
      - server
    build:
      context: client
      dockerfile: Dockerfile
    command: sh -c "npm run start:prod"
    expose:
      - 3001
    restart: always
    networks:
      - net

networks:
  net:
